# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Bump Build Number & Deploy to TestFlight"
  lane :on_merge do |options|
    # Increment Build Number	
    analyze_commits(match: 'beta/*.*.*')
    next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]
    increment_build_number(build_number: next_version)

    # Increment Version Number
    analyze_commits(match: '*.*.*')
    next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]
    increment_version_number(version_number: next_version)

    build_ios_app(
      export_method: "app-store"
    )

    # Upload Build
    notes = conventional_changelog(format: 'plain')

    upload_to_testflight(
      changelog: notes,
      api_key: options[:api_key]
    )
  end
end
